### ISSUE TITLE
The task.state are never changed,why?

### ISSUE THREAD

**Issue by GeekWolfBoy** [miguelgrinberg/flask-celery-example#17]
![image](https://user-images.githubusercontent.com/12298523/41083941-3dfa1e7c-6a65-11e8-8eb8-dd3142ee550f.png)

**Comment by miguelgrinberg** [comment]
Are you running one or more Celery workers?

**Comment by GeekWolfBoy** [comment]
It's my mistake,I was misunderstand that our programe can make Celery worker runing.
The truth is that we must running one or more  Celery workers before runing our programe by hand,our program just create tasks to the Celery workers.
thx miguelgrinberg
