### ISSUE TITLE
Feature - processing input json

### ISSUE THREAD

**Issue by saravananpsg** [miguelgrinberg/flask-celery-example#21]
Is it possible to process input json using celery from multiple client ? If so, kindly advice how to process the input files in asynchronous mode.

**Comment by miguelgrinberg** [comment]
You can pass the JSON data that you receive with your request to a background task for processing. There isn't really any difference with the examples in this repository, you just need to replace the background function with one that performs the processing logic that you need in your application.

**Comment by saravananpsg** [comment]
@miguelgrinberg Thank you!
