### ISSUE TITLE
Question: Your code works even though you do not initialize celery backend

### ISSUE THREAD

**Issue by VinayKadalagi** [miguelgrinberg/flask-celery-example#25]
I ran your code locally and it works well. 
I build  similar system of long running task and capturing custom states. But in my case it fails with  this error 

> https://stackoverflow.com/questions/31852219/why-asyncresult-returns-nonetype-after-task-is-done 

And it is resolved after i initialized celery object with backend as below,

` celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'], backend=app.config['CELERY_RESULT_BACKEND'])`

Please let me know how it is working in your case.??

**Comment by miguelgrinberg** [comment]
The result backend is in the Flask config dictionary, which then is applied to the Celery instance with:

    celery.conf.update(app.config)

Have you done that?
